<div class="row g-4">
    <div class="col-xl-8">
        <div class="card"><div class="card-header"><h2 class="card-title">Nội dung dự án</h2></div><div class="card-body">
            <div class="mb-3"><label class="form-label" for="title">Tên dự án *</label><input id="title" name="title" class="form-control" value="{{ old('title', $project->title) }}" required maxlength="255"></div>
            <div class="mb-3"><label class="form-label" for="slug">Slug</label><input id="slug" name="slug" class="form-control" value="{{ old('slug', $project->slug) }}" maxlength="255"><div class="form-text">Để trống để tự tạo từ tên.</div></div>
            <div class="mb-3"><label class="form-label" for="summary">Mô tả ngắn</label><textarea id="summary" name="summary" class="form-control" rows="3" maxlength="1000">{{ old('summary', $project->summary) }}</textarea></div>
            @foreach([['description','Mô tả chi tiết'],['design_concept','Ý tưởng thiết kế'],['construction_solution','Giải pháp thi công'],['floor_plan_description','Mô tả mặt bằng']] as [$field,$label])<div class="mb-3"><label class="form-label" for="{{ $field }}">{{ $label }}</label><textarea id="{{ $field }}" name="{{ $field }}" class="form-control" rows="6" maxlength="30000">{{ old($field, $project->{$field}) }}</textarea></div>@endforeach
        </div></div>
        <div class="card"><div class="card-header"><h2 class="card-title">Hình ảnh</h2></div><div class="card-body"><div class="mb-3"><label class="form-label" for="cover_image">Ảnh đại diện</label><input class="form-control" type="file" id="cover_image" name="cover_image" accept="image/jpeg,image/png,image/webp"><div class="form-text">JPG, PNG hoặc WebP; tối đa 8 MB.</div></div><div class="mb-3"><label class="form-label" for="gallery">Gallery</label><input class="form-control" type="file" id="gallery" name="gallery[]" accept="image/jpeg,image/png,image/webp" multiple></div><div><label class="form-label" for="floor_plans">Bản vẽ mặt bằng</label><input class="form-control" type="file" id="floor_plans" name="floor_plans[]" accept="image/jpeg,image/png,image/webp" multiple></div></div></div>
    </div>
    <div class="col-xl-4">
        <div class="card"><div class="card-header"><h2 class="card-title">Thông tin</h2></div><div class="card-body">
            <div class="mb-3"><label class="form-label" for="category_id">Danh mục *</label><select id="category_id" name="category_id" class="form-select" required><option value="">Chọn danh mục</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $project->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
            @foreach([['client','Chủ đầu tư'],['location','Địa điểm'],['style','Phong cách']] as [$field,$label])<div class="mb-3"><label class="form-label" for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" class="form-control" value="{{ old($field, $project->{$field}) }}" maxlength="255"></div>@endforeach
            <div class="row"><div class="col-6 mb-3"><label class="form-label" for="area">Diện tích</label><input id="area" name="area" type="number" step="0.01" min="0" class="form-control" value="{{ old('area', $project->area) }}"></div><div class="col-6 mb-3"><label class="form-label" for="completion_year">Năm</label><input id="completion_year" name="completion_year" type="number" min="1900" max="2100" class="form-control" value="{{ old('completion_year', $project->completion_year) }}"></div></div>
            <div class="mb-3"><label class="form-label" for="status">Trạng thái</label><select id="status" name="status" class="form-select"><option value="draft" @selected(old('status', $project->status ?: 'draft') === 'draft')>Bản nháp</option><option value="published" @selected(old('status', $project->status) === 'published')>Xuất bản</option></select></div>
            <div class="mb-3"><label class="form-label" for="published_at">Ngày xuất bản</label><input id="published_at" name="published_at" type="datetime-local" class="form-control" value="{{ old('published_at', $project->published_at?->format('Y-m-d\TH:i')) }}"></div>
            <div class="mb-3"><label class="form-label" for="sort_order">Thứ tự</label><input id="sort_order" name="sort_order" type="number" min="0" class="form-control" value="{{ old('sort_order', $project->sort_order ?? 0) }}"></div>
            <div class="form-check"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" type="checkbox" name="is_featured" value="1" id="is_featured" @checked(old('is_featured', $project->is_featured))><label class="form-check-label" for="is_featured">Dự án nổi bật</label></div>
        </div><div class="card-footer"><button class="btn btn-primary w-100" type="submit"><i class="bi bi-save"></i> Lưu dự án</button></div></div>
    </div>
</div>
