<?php

$field = static fn (string $key, string $label, string $fallback, string $type = 'text', int $max = 160): array => compact('key', 'label', 'fallback', 'type', 'max');
$section = static fn (string $key, string $title, string $description, array $fields): array => compact('key', 'title', 'description', 'fields');

return [
    'services' => [
        'title' => 'Trang Dịch vụ',
        'description' => 'Điều chỉnh phần giới thiệu, các tiêu đề section và lời kêu gọi hành động. Danh sách dịch vụ được quản lý ở mục Dịch vụ.',
        'preview_route' => 'services.index',
        'group' => 'page_services',
        'sections' => [
            $section('hero', 'Hero đầu trang', 'Thông điệp chính khi khách hàng mở trang Dịch vụ.', [
                $field('services_hero_kicker', 'Nhãn nhỏ', 'Chuyên môn ACONS'),
                $field('services_hero_title', 'Tiêu đề', 'Giải pháp toàn diện'),
                $field('services_hero_accent', 'Dòng nhấn', 'biến ý tưởng thành hiện thực'),
                $field('services_hero_description', 'Mô tả', 'Từ kiến trúc, nội thất đến thi công và quy hoạch, ACONS kết nối tư duy thiết kế với năng lực triển khai để tạo nên những công trình có giá trị lâu dài.', 'textarea', 500),
                $field('services_hero_primary_button', 'Nút chính', 'Khám phá dịch vụ', 'text', 80),
                $field('services_hero_secondary_button', 'Nút phụ', 'Yêu cầu tư vấn', 'text', 80),
            ]),
            $section('headings', 'Các vùng nội dung', 'Tiêu đề và mô tả cho những section chính.', [
                $field('services_overview_kicker', 'Tổng quan · Nhãn nhỏ', 'Năng lực chuyên môn'),
                $field('services_overview_title', 'Tổng quan · Tiêu đề', 'Hệ dịch vụ được tích hợp'),
                $field('services_overview_description', 'Tổng quan · Mô tả', 'ACONS cung cấp một hệ giải pháp liên kết chặt chẽ, hỗ trợ dự án từ nghiên cứu ban đầu đến thiết kế, triển khai và hoàn thiện.', 'textarea', 500),
                $field('services_detail_kicker', 'Chi tiết · Nhãn nhỏ', 'Chi tiết dịch vụ'),
                $field('services_detail_title', 'Chi tiết · Tiêu đề', 'ACONS mang đến điều gì?'),
                $field('services_difference_kicker', 'Khác biệt · Nhãn nhỏ', 'Khác biệt ACONS'),
                $field('services_difference_title', 'Khác biệt · Tiêu đề', 'Vì sao khách hàng chọn ACONS?'),
                $field('services_process_kicker', 'Quy trình · Nhãn nhỏ', 'Cách chúng tôi làm việc'),
                $field('services_process_title', 'Quy trình · Tiêu đề', 'Quy trình triển khai'),
                $field('services_partners_kicker', 'Đối tác · Nhãn nhỏ', 'Khách hàng & đối tác'),
                $field('services_partners_title', 'Đối tác · Tiêu đề', 'Hệ sinh thái đồng hành'),
                $field('services_faq_kicker', 'FAQ · Nhãn nhỏ', 'Câu hỏi thường gặp'),
                $field('services_faq_title', 'FAQ · Tiêu đề', 'Bạn đang cần làm rõ điều gì?'),
                $field('services_faq_description', 'FAQ · Mô tả', 'Trao đổi trực tiếp với đội ngũ ACONS để nhận tư vấn phù hợp với loại hình và giai đoạn dự án của bạn.', 'textarea', 500),
            ]),
            $section('technology', 'Khối công nghệ', 'Thông điệp về công nghệ hỗ trợ quy trình thiết kế.', [
                $field('services_technology_kicker', 'Nhãn nhỏ', 'Đổi mới'),
                $field('services_technology_title', 'Tiêu đề', 'Thiết kế được hỗ trợ bởi công nghệ'),
                $field('services_technology_description', 'Mô tả', 'ACONS sử dụng công nghệ như một công cụ để kiểm chứng ý tưởng, phối hợp hồ sơ và giúp khách hàng hình dung không gian trước khi thi công.', 'textarea', 500),
            ]),
            $section('cta', 'CTA cuối trang', 'Lời mời khách hàng bắt đầu dự án.', [
                $field('services_cta_kicker', 'Nhãn nhỏ', 'Bắt đầu cùng ACONS'),
                $field('services_cta_title', 'Tiêu đề', 'Sẵn sàng cho dự án tiếp theo?'),
                $field('services_cta_description', 'Mô tả', 'Hãy chia sẻ mục tiêu của bạn để đội ngũ ACONS đề xuất phạm vi dịch vụ phù hợp.', 'textarea', 500),
                $field('services_cta_primary_button', 'Nút chính', 'Nhận tư vấn', 'text', 80),
            ]),
        ],
    ],
    'contact' => [
        'title' => 'Trang Liên hệ',
        'description' => 'Điều chỉnh thông điệp tư vấn và nội dung hướng dẫn. Hotline, email, địa chỉ và bản đồ nằm trong Cấu hình website.',
        'preview_route' => 'contacts.create',
        'group' => 'page_contact',
        'sections' => [
            $section('hero', 'Hero đầu trang', 'Thông điệp mở đầu trang liên hệ.', [
                $field('contact_hero_kicker', 'Nhãn nhỏ', 'Kết nối cùng ACONS'),
                $field('contact_hero_title', 'Tiêu đề', 'Cùng bắt đầu một công trình mới'),
                $field('contact_hero_description', 'Mô tả', 'Chia sẻ nhu cầu của bạn để đội ngũ ACONS tư vấn định hướng phù hợp cho công trình đang ấp ủ.', 'textarea', 500),
                $field('contact_hero_primary_button', 'Nút chính', 'Liên hệ ngay', 'text', 80),
                $field('contact_hero_secondary_button', 'Nút phụ', 'Chọn dịch vụ tư vấn', 'text', 80),
            ]),
            $section('form', 'Dịch vụ & biểu mẫu', 'Nội dung dẫn người dùng đến biểu mẫu tư vấn.', [
                $field('contact_services_kicker', 'Chọn dịch vụ · Nhãn nhỏ', 'Dịch vụ'),
                $field('contact_services_title', 'Chọn dịch vụ · Tiêu đề', 'Bạn đang quan tâm đến điều gì?'),
                $field('contact_services_description', 'Chọn dịch vụ · Mô tả', 'Chọn một dịch vụ để chúng tôi chuyển yêu cầu của bạn đến đúng nhóm chuyên môn.', 'textarea', 500),
                $field('contact_form_kicker', 'Biểu mẫu · Nhãn nhỏ', 'Gửi yêu cầu tư vấn'),
                $field('contact_form_title', 'Biểu mẫu · Tiêu đề', 'Hãy kể chúng tôi về dự án của bạn'),
                $field('contact_form_description', 'Biểu mẫu · Mô tả', 'Chia sẻ nhu cầu thiết kế, phạm vi công việc hoặc mong muốn của bạn. Đội ngũ ACONS sẽ xem xét kỹ và phản hồi bằng một hướng tiếp cận phù hợp.', 'textarea', 600),
            ]),
            $section('support', 'Vị trí & hỗ trợ', 'Các tiêu đề hỗ trợ khách hàng trước khi liên hệ.', [
                $field('contact_location_kicker', 'Vị trí · Nhãn nhỏ', 'Tìm chúng tôi'),
                $field('contact_location_title', 'Vị trí · Tiêu đề', 'Văn phòng ACONS'),
                $field('contact_why_kicker', 'Lý do · Nhãn nhỏ', 'Vì sao chọn ACONS'),
                $field('contact_why_title', 'Lý do · Tiêu đề', 'Đối tác phù hợp cho một công trình khác biệt'),
                $field('contact_faq_kicker', 'FAQ · Nhãn nhỏ', 'Câu hỏi thường gặp'),
                $field('contact_faq_title', 'FAQ · Tiêu đề', 'Những điều bạn có thể muốn biết'),
                $field('contact_faq_description', 'FAQ · Mô tả', 'Nếu chưa tìm thấy câu trả lời phù hợp, hãy gửi email hoặc gọi trực tiếp cho đội ngũ ACONS.', 'textarea', 500),
            ]),
            $section('cta', 'CTA cuối trang', 'Lời mời bắt đầu trao đổi.', [
                $field('contact_cta_title', 'Tiêu đề', 'Sẵn sàng bắt đầu dự án tiếp theo?'),
                $field('contact_cta_description', 'Mô tả', 'Đội ngũ ACONS sẵn sàng cùng bạn biến ý tưởng thành một không gian có giá trị lâu dài.', 'textarea', 500),
                $field('contact_cta_primary_button', 'Nút chính', 'Đặt lịch tư vấn', 'text', 80),
                $field('contact_cta_secondary_button', 'Nút phụ', 'Khám phá dự án', 'text', 80),
            ]),
        ],
    ],
    'about' => [
        'title' => 'Trang Giới thiệu',
        'description' => 'Quản lý câu chuyện thương hiệu, giá trị, đội ngũ và hành trình ACONS.',
        'preview_route' => 'about.index',
        'group' => 'page_about',
        'sections' => [
            $section('hero', 'Hero đầu trang', 'Thông điệp định vị thương hiệu.', [
                $field('about_hero_kicker', 'Nhãn nhỏ', 'Kiến trúc · Nội thất · Xây dựng'),
                $field('about_hero_title', 'Tiêu đề', 'Chúng tôi kiến tạo'),
                $field('about_hero_accent', 'Dòng nhấn', 'giá trị vượt thời gian'),
                $field('about_hero_description', 'Mô tả', 'ACONS là tập thể kiến trúc sư, kỹ sư và nhà quản lý cùng theo đuổi một mục tiêu: biến những yêu cầu phức tạp thành không gian rõ ràng, tinh tế và bền vững.', 'textarea', 600),
                $field('about_hero_primary_button', 'Nút chính', 'Câu chuyện ACONS', 'text', 80),
                $field('about_hero_secondary_button', 'Nút phụ', 'Làm việc cùng chúng tôi', 'text', 80),
            ]),
            $section('story', 'Câu chuyện ACONS', 'Giới thiệu triết lý hình thành và cách làm việc.', [
                $field('about_story_kicker', 'Nhãn nhỏ', 'Câu chuyện ACONS'),
                $field('about_story_title', 'Tiêu đề', 'Bắt đầu từ niềm tin vào thiết kế tử tế'),
                $field('about_story_lead', 'Đoạn dẫn', 'Một công trình có giá trị không chỉ đẹp ở ngày bàn giao, mà còn cần phù hợp với con người, khí hậu và cách nó được sử dụng trong nhiều năm sau đó.', 'textarea', 600),
                $field('about_story_body', 'Nội dung', 'Vì vậy, ACONS kết nối thiết kế và thi công trong một quy trình thống nhất. Mỗi quyết định đều được cân nhắc trên ba phương diện: trải nghiệm không gian, tính khả thi và giá trị dài hạn.', 'textarea', 800),
            ]),
            $section('identity', 'Giá trị & đội ngũ', 'Các tiêu đề giới thiệu văn hóa và năng lực con người.', [
                $field('about_values_kicker', 'Giá trị · Nhãn nhỏ', 'Giá trị cốt lõi'),
                $field('about_values_title', 'Giá trị · Tiêu đề', 'Nguyên tắc dẫn lối mọi quyết định'),
                $field('about_values_description', 'Giá trị · Mô tả', 'Những giá trị này định hình cách ACONS lắng nghe, thiết kế, phối hợp và chịu trách nhiệm với từng công trình.', 'textarea', 500),
                $field('about_team_kicker', 'Đội ngũ · Nhãn nhỏ', 'Đội ngũ liên ngành'),
                $field('about_team_title', 'Đội ngũ · Tiêu đề', 'Một góc nhìn chung, nhiều chuyên môn'),
                $field('about_team_description', 'Đội ngũ · Mô tả', 'Kiến trúc sư, kỹ sư kết cấu, kỹ sư MEP và đội ngũ triển khai cùng tham gia từ sớm. Sự phối hợp này giúp ý tưởng được bảo toàn khi đi vào thực tế.', 'textarea', 600),
                $field('about_journey_kicker', 'Hành trình · Nhãn nhỏ', 'Hành trình phát triển'),
                $field('about_journey_title', 'Hành trình · Tiêu đề', 'Từng bước xây dựng một hệ sinh thái đồng bộ'),
            ]),
            $section('cta', 'Đối tác & CTA', 'Thông điệp ở cuối trang Giới thiệu.', [
                $field('about_partners_kicker', 'Đối tác · Nhãn nhỏ', 'Hệ sinh thái'),
                $field('about_partners_title', 'Đối tác · Tiêu đề', 'Những đối tác cùng tạo nên giá trị'),
                $field('about_partners_description', 'Đối tác · Mô tả', 'ACONS xây dựng mạng lưới đối tác vật liệu, kỹ thuật và công nghệ để mỗi giải pháp đều có khả năng triển khai thực tế.', 'textarea', 500),
                $field('about_cta_kicker', 'CTA · Nhãn nhỏ', 'Bắt đầu cùng ACONS'),
                $field('about_cta_title', 'CTA · Tiêu đề', 'Cùng tạo nên một công trình có giá trị lâu dài'),
                $field('about_cta_description', 'CTA · Mô tả', 'Chia sẻ với chúng tôi về ý tưởng, khu đất và mục tiêu của bạn.', 'textarea', 500),
                $field('about_cta_button', 'CTA · Nút', 'Kết nối với ACONS', 'text', 80),
            ]),
        ],
    ],
    'epsilon' => [
        'title' => 'Trang Epsilon',
        'description' => 'Quản lý thông điệp về BIM, AI và quy trình số của bộ phận công nghệ ACONS.',
        'preview_route' => 'epsilon.index',
        'group' => 'page_epsilon',
        'sections' => [
            $section('hero', 'Hero đầu trang', 'Định vị Epsilon và lời mời trao đổi.', [
                $field('epsilon_hero_kicker', 'Nhãn nhỏ', 'ACONS Technology Division'),
                $field('epsilon_hero_title', 'Tiêu đề', 'Công nghệ cho những công trình chính xác hơn'),
                $field('epsilon_hero_description', 'Mô tả', 'Epsilon biến dữ liệu thiết kế thành một ngôn ngữ chung, giúp chủ đầu tư, kiến trúc sư và kỹ sư phối hợp nhanh hơn trong toàn bộ vòng đời dự án.', 'textarea', 600),
                $field('epsilon_hero_primary_button', 'Nút chính', 'Khám phá giải pháp', 'text', 80),
                $field('epsilon_hero_secondary_button', 'Nút phụ', 'Trao đổi cùng chuyên gia', 'text', 80),
            ]),
            $section('capabilities', 'Năng lực số', 'Thông điệp tổng quan và các nền tảng chính.', [
                $field('epsilon_capabilities_kicker', 'Nhãn nhỏ', 'Năng lực số'),
                $field('epsilon_capabilities_title', 'Tiêu đề', 'Một hệ công nghệ cho toàn dự án'),
                $field('epsilon_capabilities_description', 'Mô tả', 'Công nghệ không thay thế tư duy thiết kế. Epsilon giúp đội ngũ ACONS kiểm chứng ý tưởng, nhận diện xung đột sớm và kiểm soát từng thay đổi bằng dữ liệu.', 'textarea', 600),
                $field('epsilon_bim_title', 'BIM · Tiêu đề', 'Thấy vấn đề trước khi nó xuất hiện tại công trường'),
                $field('epsilon_bim_description', 'BIM · Mô tả', 'Mô hình BIM cho phép các bộ môn làm việc trên cùng một nguồn thông tin, giảm sai khác giữa thiết kế và thi công.', 'textarea', 500),
                $field('epsilon_ai_title', 'AI Lab · Tiêu đề', 'Tri thức dự án được kích hoạt'),
                $field('epsilon_ai_description', 'AI Lab · Mô tả', 'AI Lab là không gian thử nghiệm các công cụ hỗ trợ đội ngũ đánh giá dữ liệu, so sánh phương án và tìm kiếm thông tin kỹ thuật nhanh hơn.', 'textarea', 500),
            ]),
            $section('workflow', 'Quy trình số', 'Nội dung về dòng thông tin và ứng dụng thực tế.', [
                $field('epsilon_workflow_kicker', 'Quy trình · Nhãn nhỏ', '03 / Digital workflow'),
                $field('epsilon_workflow_title', 'Quy trình · Tiêu đề', 'Dòng thông tin không đứt gãy'),
                $field('epsilon_workflow_description', 'Quy trình · Mô tả', 'Từ brief ban đầu đến hồ sơ bàn giao, mỗi quyết định đều có ngữ cảnh, người phụ trách và trạng thái rõ ràng.', 'textarea', 500),
                $field('epsilon_projects_kicker', 'Dự án · Nhãn nhỏ', 'Ứng dụng thực tế'),
                $field('epsilon_projects_title', 'Dự án · Tiêu đề', 'Dự án được hỗ trợ bởi dữ liệu'),
            ]),
            $section('cta', 'CTA cuối trang', 'Lời mời ứng dụng công nghệ vào dự án.', [
                $field('epsilon_cta_kicker', 'Nhãn nhỏ', 'Kết nối công nghệ và thiết kế'),
                $field('epsilon_cta_title', 'Tiêu đề', 'Bắt đầu một dự án thông minh hơn'),
                $field('epsilon_cta_description', 'Mô tả', 'Chia sẻ bài toán của bạn để ACONS và Epsilon đề xuất luồng triển khai phù hợp.', 'textarea', 500),
                $field('epsilon_cta_button', 'Nút', 'Trao đổi cùng chúng tôi', 'text', 80),
            ]),
        ],
    ],
    'resources' => [
        'title' => 'Trang Tài nguyên',
        'description' => 'Quản lý thông điệp của trung tâm kiến thức. Danh sách bài viết và dự án được lấy từ các mục quản lý tương ứng.',
        'preview_route' => 'resources.index',
        'group' => 'page_resources',
        'sections' => [
            $section('hero', 'Hero đầu trang', 'Giới thiệu trung tâm tài nguyên ACONS.', [
                $field('resources_hero_kicker', 'Nhãn nhỏ', 'Trung tâm kiến thức ACONS'),
                $field('resources_hero_title', 'Tiêu đề', 'Góc nhìn tạo nên công trình bền vững'),
                $field('resources_hero_description', 'Mô tả', 'Khám phá hồ sơ dự án, kinh nghiệm thiết kế, kiến thức thi công và những câu chuyện đang định hình cách ACONS kiến tạo không gian.', 'textarea', 600),
                $field('resources_hero_primary_button', 'Nút chính', 'Bài viết mới nhất', 'text', 80),
                $field('resources_hero_secondary_button', 'Nút phụ', 'Xem hồ sơ dự án', 'text', 80),
            ]),
            $section('content', 'Bài viết & dự án', 'Tiêu đề cho hai nguồn nội dung động.', [
                $field('resources_articles_kicker', 'Bài viết · Nhãn nhỏ', 'Mới nhất'),
                $field('resources_articles_title', 'Bài viết · Tiêu đề', 'Góc nhìn chuyên môn'),
                $field('resources_articles_description', 'Bài viết · Mô tả', 'Những phân tích ngắn gọn giúp chủ đầu tư hiểu rõ hơn về không gian, vật liệu, chi phí và quy trình triển khai.', 'textarea', 500),
                $field('resources_projects_kicker', 'Dự án · Nhãn nhỏ', 'Hồ sơ dự án'),
                $field('resources_projects_title', 'Dự án · Tiêu đề', 'Giải pháp phía sau mỗi công trình'),
            ]),
            $section('guides', 'Cẩm nang', 'Nội dung dẫn đến các khu vực hữu ích của website.', [
                $field('resources_guides_kicker', 'Nhãn nhỏ', 'Cẩm nang ACONS'),
                $field('resources_guides_title', 'Tiêu đề', 'Kiến thức cần biết trước khi bắt đầu'),
                $field('resources_guides_description', 'Mô tả', 'Các nội dung được tổ chức theo từng giai đoạn để bạn dễ tìm đúng thông tin đang cần.', 'textarea', 500),
                $field('resources_news_label', 'Tin tức · Nhãn', 'Tin tức ACONS'),
                $field('resources_news_description', 'Tin tức · Mô tả', 'Theo dõi hoạt động mới, câu chuyện công trường và các chương trình chuyên môn của đội ngũ.', 'textarea', 500),
                $field('resources_news_button', 'Tin tức · Nút', 'Kết nối với ACONS', 'text', 80),
            ]),
        ],
    ],
];
