<?php

return [
    'title' => 'ACONS Admin',
    'title_prefix' => '',
    'title_postfix' => ' | ACONS',
    'use_ico_only' => false,
    'use_full_favicon' => false,
    'google_fonts' => ['allowed' => false],

    'logo' => '<b>ACONS</b> Admin',
    'logo_img' => false,
    'classes_brand_text' => 'fw-light',

    'usermenu_enabled' => true,
    'usermenu_header' => false,
    'usermenu_image' => false,
    'usermenu_desc' => false,
    'usermenu_profile_url' => false,

    'layout_topnav' => false,
    'layout_boxed' => false,
    'layout_fixed_sidebar' => true,
    'layout_fixed_navbar' => true,
    'layout_fixed_footer' => false,
    'layout_dark_mode' => null,
    'layout_rtl' => false,
    'sidebar_breakpoint' => 'lg',
    'sidebar_mini' => true,
    'sidebar_collapse' => false,
    'sidebar_collapse_auto_size' => false,
    'sidebar_scrollbar_theme' => 'os-theme-light',
    'sidebar_scrollbar_auto_hide' => 'leave',
    'sidebar_theme' => 'dark',

    'primary_color' => '#1f3a32',
    'sidebar_color' => '#14251f',
    'navbar_color' => '#ffffff',
    'footer_color' => '#ffffff',
    'classes_body' => '',
    'classes_brand' => '',
    'classes_content_wrapper' => '',
    'classes_content_header' => '',
    'classes_content' => '',
    'classes_sidebar' => 'text-bg-dark shadow',
    'classes_sidebar_nav' => '',
    'classes_topnav' => 'navbar-expand bg-body',
    'classes_topnav_nav' => 'navbar',
    'classes_topnav_container' => 'container-fluid',
    'color_mode_toggle' => true,

    'footer_left' => '© '.date('Y').' ACONS. All rights reserved.',
    'footer_right' => 'Laravel + AdminLTE 4',
    'preloader' => false,
    'control_sidebar' => false,
    'demo' => false,
    'docs' => false,
    'sidebar_docs_url' => false,

    'menu' => [
        ['header' => 'TỔNG QUAN'],
        ['text' => 'Dashboard', 'route' => 'admin.dashboard', 'icon' => 'bi bi-speedometer2', 'active' => ['admin']],
        ['header' => 'NỘI DUNG'],
        ['text' => 'Dự án', 'route' => 'admin.projects.index', 'icon' => 'bi bi-buildings', 'active' => ['admin/projects*']],
        ['text' => 'Danh mục', 'route' => 'admin.categories.index', 'icon' => 'bi bi-tags', 'active' => ['admin/categories*']],
        ['text' => 'Dịch vụ', 'route' => 'admin.services.index', 'icon' => 'bi bi-grid', 'active' => ['admin/services*']],
        ['header' => 'KHÁCH HÀNG'],
        ['text' => 'Yêu cầu tư vấn', 'route' => 'admin.contacts.index', 'icon' => 'bi bi-chat-left-text', 'active' => ['admin/contacts*']],
        ['header' => 'HỆ THỐNG'],
        ['text' => 'Cấu hình', 'route' => 'admin.settings.edit', 'icon' => 'bi bi-gear', 'active' => ['admin/settings*']],
        ['text' => 'Xem website', 'route' => 'home', 'icon' => 'bi bi-box-arrow-up-right', 'target' => '_blank'],
    ],

    'plugins' => [],
];
